apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "usg-est-issuer.fullname" . }}
  labels:
    {{- include "usg-est-issuer.labels" . | nindent 4 }}
rules:
  - apiGroups: ["pki.usg.mil"]
    resources: ["estissuers"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["cert-manager.io"]
    resources: ["certificaterequests"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["cert-manager.io"]
    resources: ["certificaterequests/status"]
    verbs: ["get", "patch", "update"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "usg-est-issuer.fullname" . }}
  labels:
    {{- include "usg-est-issuer.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "usg-est-issuer.fullname" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "usg-est-issuer.fullname" . }}
