image:
  repository: ghcr.io/192d-wing/usg-est-issuer
  tag: "0.1.0"
  digest: ""
  pullPolicy: IfNotPresent

logLevel: info

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 256Mi

podAnnotations: {}
nodeSelector: {}
tolerations: []
affinity: {}
